<?php

namespace App\Repositories\Eloquents;

use App\Models\AdminGroup;
use App\Repositories\Contracts\AdminGroupContract;
use Illuminate\Database\Eloquent\Model;


class AdminGroupRepositoryEloquent extends BaseRepositoryEloquent implements AdminGroupContract
{
    public function getModel(): Model
    {
        return new AdminGroup;
    }

    public function filter($condition = [], $with = [], $columns = ['*'], $query = null)
    {
        $query = $query ?? $this->model;
        $query = $query->withCount(['admins'])->where('key','<>',SUPER_ADMIN);
        return parent::filter($condition, $with, $columns, $query); // TODO: Change the autogenerated stub
    }

    public function options($condition = [], $column = ['id', 'name'], $query = null)
    {
        $query = $query ?? $this->model;
        $query = $query->where('key','<>',SUPER_ADMIN);
        return parent::options($condition, $column, $query); // TODO: Change the autogenerated stub
    }

}
